environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVARS_FILE: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat
      VCVARS_ARG:
      ENABLE_UI: ON
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VCVARS_FILE: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
      VCVARS_ARG:
      ENABLE_UI: ON

install:
  - call "%VCVARS_FILE%" %VCVARS_ARG%

before_build:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "NMake Makefiles" -DENABLE_TESTS=ON -DENABLE_UI=%ENABLE_UI%
  - nmake
  - ctest --output-on-failure
